description: Base de la majoration pour le régime général des Allocation de la mère au foyer (AMF, 1955-1977)
values:
  1976-07-01:
    value: 388.2
  1978-01-01:
    value: null
metadata:
  ux_name: Base
  unit: currency
  ipp_csv_id: maj_gene_base
  reference:
    1978-01-01:
      title: Loi 77-765 du 12/07/1977
      href: https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000000886344
    1976-07-01: Décret 76-1084 du 29/11/1976 (majoration)
  official_journal_date:
    1978-01-01: 1977-07-13
    1976-07-01: 1976-12-01
  notes:
    1976-07-01: Remplacé par le "complément familial" depuis 01/01/1978
  description_en: "Allowance for stay-at-home-mother (AMF): Extra allowances"
documentation: |
  Notes :
   La majoration est instituée par la loi 72-8 du 3 janvier 1972, art 2
