###############################################################################
## Fichier de description du package pour Anaconda.org
## Attention, les chaines PYPI_VERSION, PYPI_URL et PYPI_SHA256 sont remplacées
## par la CI, il faut les conserver.
###############################################################################

{% set name = "OpenFisca-France" %}
{% set version = "PYPI_VERSION" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: PYPI_URL
  sha256: PYPI_SHA256

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.6,<4.0
    - OpenFisca-Core >=35.2.0,<36.0


test:
  imports:
    - openfisca_france
  requires:
    - pip
    - pytest >=4.4.1,<6.0.0  # To be Removed when OF-Core as been updated
  commands:
    - pip check

outputs:
  - name: openfisca-france

  - name: openfisca-france-scipy
    build:
      noarch: python
    requirements:
      host:
        - python
      run:
        - scipy >=0.17
        - {{ pin_subpackage('openfisca-france', exact=True) }}

  - name: openfisca-france-dev
    build:
      noarch: python
    requirements:
      host:
        - python
      run:
        - autopep8 ==1.5.7
        - flake8 >=3.8.0,<3.10.0
        - flake8-print
        - pytest >=5.0.0, <7.0.0
        - requests >=2.8
        - yamllint >=1.11.1,<1.27
        - {{ pin_subpackage('openfisca-france-scipy', exact=True) }}

about:
  home: https://fr.openfisca.org/
  # Use the SPDX identifier, e.g: GPL-2.0-only instead of GNU General Public License version 2.0
  # See https://spdx.org/licenses/
  license_family: AGPL
  license: AGPL-3.0-only
  license_file: ../LICENSE.AGPL.txt
  summary: "French tax and benefit system for OpenFisca"
  description: |
    OpenFisca is a versatile microsimulation free software.
    This repository contains the OpenFisca model of the French tax and benefit system.
    Therefore, the working language here is French.
  doc_url: https://fr.openfisca.org/
  dev_url: https://github.com/openfisca/openfisca-france/

extra:
  recipe-maintainers:
    # GitHub IDs for maintainers of the recipe.
    # Always check with the people listed below if they are OK becoming maintainers of the recipe. (There will be spam!)
    - benoit-cty
