name: Hermine

on:
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    tortellini:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            # - uses: tortellini-tools/action@v3
            - uses: eraviart/tortellini-action@v4.0.9
            - uses: actions/upload-artifact@v2
              with:
                  name: tortellini-result
                  path: .tortellini/out
            - run : "curl -H 'Authorization: Token ${{ secrets.HERMINE_TOKEN }}' https://chantier.hermine-foss.org/api/upload_ort/ -X PUT -F 'ort_file=@.tortellini/out/evaluated-model.json' -F 'release_id=1'"
                
