name: Hermine

on:
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    tortellini_hermine:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            # - uses: tortellini-tools/action@v3
            - uses: eraviart/tortellini-action@v4.0.9
            - uses: actions/upload-artifact@v2
              with:
                  name: tortellini-result
                  path: .tortellini/out
            - run : mkdir .hermine
              if: ${{ success() }}
            - run : "curl -X PUT https://chantier.hermine-foss.org/api/upload_ort/ -H 'Authorization: Token ${{ secrets.HERMINE_TOKEN }}' -F 'ort_file=@.tortellini/out/evaluated-model.json' -F 'release_id=1' --silent"
              if: ${{ success() }}
            - run : "curl https://chantier.hermine-foss.org/api/releases/1/validation-1/ -H 'Authorization: Token ${{ secrets.HERMINE_TOKEN }}' --output .hermine/validation-1.json --silent"
              if: ${{ success() }}
            - run : "curl https://chantier.hermine-foss.org/api/releases/1/validation-2/ -H 'Authorization: Token ${{ secrets.HERMINE_TOKEN }}' --output .hermine/validation-2.json --silent"
              if: ${{ success() }}
            - run : "curl https://chantier.hermine-foss.org/api/releases/1/validation-3/ -H 'Authorization: Token ${{ secrets.HERMINE_TOKEN }}' --output .hermine/validation-3.json --silent"
              if: ${{ success() }}
            - run : "curl https://chantier.hermine-foss.org/api/releases/1/validation-4/ -H 'Authorization: Token ${{ secrets.HERMINE_TOKEN }}' --output .hermine/validation-4.json --silent"
              if: ${{ success() }}
  
 
