name: publish_conda

on: [push]

#on:
#  release:
#    types: [published]

jobs:
  publish-to-conda:
    name: publish-to-conda (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.7"]
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all the tags
      - name: Conda info
        shell: bash -l {0}
        run: conda info
      - name: Conda list
        shell: pwsh
        run: conda list
      - name: build
        run: conda install conda-build anaconda-client && conda build .conda
      - name: publish
        run: anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload -u openfisca
