name: publish_conda

on: [push]

#on:
#  release:
#    types: [published]
    
jobs:
  publish-to-conda:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: publish-to-conda
      uses: fcakyon/conda-publish-action@v1.3
      continue-on-error: true
      with:
        subdir: '.conda'
        anacondatoken: ${{ secrets.ANACONDA_TOKEN }}
        platforms: 'win osx linux'
